# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SerrandaManager' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for SerrandaManager
  pod 'Alamofire', '~> 4.8.2'

  target 'SerrandaManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SerrandaManagerUITests' do
    # Pods for testing
  end

end
